import {  Router } from "express";
import { container } from "tsyringe";
import { DonHangController } from "../controllers/donhangConTroller";
const DonHangRouter = Router();
const ctr = container.resolve(DonHangController);
DonHangRouter.get('/getbyid/:id', ctr.GetDonHangById.bind(ctr) );
DonHangRouter.get('/getchitietbyid/:id', ctr.GetChiTietDonHangById.bind(ctr) );
DonHangRouter.get('/getall/:pageIndex/:pageSize', ctr.GetAllDonHang.bind(ctr));
DonHangRouter.post('/updatestatus/:id', ctr.UpdateOrderStatus.bind(ctr) );
DonHangRouter.post('/updatequantity/:id/:sl', ctr.UpdateQuantity.bind(ctr) );
export default DonHangRouter;
