import {  Router } from "express";
import { container } from "tsyringe";
import { HomeController } from "../controllers/HomeController";
import { authenticate } from '../middlewares/authMiddleware';
const HomeRouter = Router();
const ctr = container.resolve(HomeController);
HomeRouter.get('/getspbyid/:id', ctr.GetSanphamById.bind(ctr) );
HomeRouter.post('/confirmOrder/:id', ctr.ConfirmOrder.bind(ctr) );
HomeRouter.get('/getkhachhangbysdt/:sdt', ctr.GetKhachHangBySdt.bind(ctr) );
HomeRouter.get('/getloaisp', ctr.GetLoaiSp.bind(ctr) );
HomeRouter.get('/gettacgia', ctr.GetTacGia.bind(ctr) );
HomeRouter.get('/getspbyloai/:id', ctr.GetSanphamByLoai.bind(ctr) );
HomeRouter.get('/getspbyname/:name', ctr.GetSanphamByName.bind(ctr) );
HomeRouter.get('/getsp/:pageIndex/:pageSize', ctr.GetSanPham.bind(ctr) );
HomeRouter.get('/getorderbysdt/:sdt', ctr.GetOrderBySdt.bind(ctr) );
HomeRouter.get('/getspbynsx/:id', ctr.GetSanphamByNsx.bind(ctr) );
HomeRouter.get('/getbytg/:id/:sl', ctr.GetSanphamByTg.bind(ctr) );
HomeRouter.get('/getspbyloaiid/:id/:sl', ctr.GetSpByLoaiId.bind(ctr) );
HomeRouter.get('/getbanchay/:sl', ctr.GetSanphamBanChay.bind(ctr));
HomeRouter.get('/getsanphammoi/:sl', ctr.GetSanphamMoi.bind(ctr));
HomeRouter.post('/createdonhang/',authenticate, ctr.CreateDonHang.bind(ctr));
export default HomeRouter;
