import {  Router } from "express";
import { container } from "tsyringe";
import { LoaiSpController } from "../controllers/loaispConstroller";
const loaispRouter = Router();
const ctr = container.resolve(LoaiSpController);
loaispRouter.get('/getbyid/:id', ctr.GetLoaiSpById.bind(ctr) );
loaispRouter.get('/getall', ctr.GetAllLoaiSp.bind(ctr));
loaispRouter.post('/create', ctr.CreateLoaiSp.bind(ctr));
loaispRouter.post('/update', ctr.UpdateLoaiSp.bind(ctr));
loaispRouter.delete('/delete/:id', ctr.DeleteLoaiSp.bind(ctr));
export default loaispRouter;
